print <<PROLOGUE;
# autogenerated from a websequencediagram script - do not edit
.PS
copy "sequence.pic";
PROLOGUE

my %object_names = (); # global list of object names
my @objects = (); # ordered list of object names

sub object {
    my $name = shift;
    if (not defined $object_names{$name}) {
        push @objects, $name;
        $object_names{$name} = 1;
    }
}

while (<>) {
    if (/^(.+?)(->|-->)(.+?): (.+)/) {
#        print STDERR "$1 arrow $2 to $3 saying $4\n";

        object($1); object($3);
        
        if ($2 eq '->') {
            push @output, ['message', 'step',  qq/message($1,$3,"$4")/];
        }
        if ($2 eq '-->') {
            push @output, ['message', 'step',  qq/rmessage($1,$3,"$4")/];
        }
    }
    if (/^activate\s+(.+)/) {
        object($1);
        push @output, ['lifetime', 'step', qq/active($1)/];
    }
    if (/^deactivate\s+(.+)/) {
        object($1);
        push @output, ['lifetime', 'step', qq/inactive($1)/];
    }
}

foreach my $i (@output) {
    my ($type, $step, $outline) = @{$i};
    print $outline, ";\n";
    if ($step) {
        print "step();\n";
    }
}

print <<EPILOGUE;
.PE
EPILOGUE

# print STDERR join(', ', @objects), "\n";
